import Foundation
import SwiftUI

@MainActor
@Observable
public final class CaptivePortalService {
    public static let shared = CaptivePortalService()
    
    public var templates: [CaptivePortalTemplate] = CaptivePortalDefaults.all
    public var selectedTemplate: CaptivePortalTemplate
    public var currentHtml: String
    public var isGenerating: Bool = false
    public var isDeploying: Bool = false
    public var lastStatus: String?
    public var lastError: String?
    
    private let piHarness = PiHarnessService.shared
    private let openRouter = OpenRouterService.shared
    private let settings = AppSettings.shared
    private let connection = FlipperConnectionManager.shared
    
    public init() {
        let initial = CaptivePortalDefaults.corporateGuestAup
        self.selectedTemplate = initial
        self.currentHtml = initial.htmlContent
    }
    
    public func selectTemplate(_ template: CaptivePortalTemplate) {
        self.selectedTemplate = template
        self.currentHtml = template.htmlContent
        self.lastStatus = "Loaded template: \(template.title)"
    }
    
    /// Use active AI engine (Pi Harness or OpenRouter) to generate/refine captive portal HTML.
    public func generatePortalWithAi(prompt: String, onDelta: ((String) -> Void)? = nil) async throws -> String {
        guard !prompt.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw NSError(domain: "CaptivePortalService", code: -1, userInfo: [NSLocalizedDescriptionKey: "Prompt cannot be empty."])
        }
        
        self.isGenerating = true
        self.lastStatus = "Consulting AI Portal Architect..."
        self.lastError = nil
        defer { self.isGenerating = false }
        
        let systemPrompt = """
You are an expert responsive web designer and frontend security engineer specialized in embedded 802.11 captive portal design.
Your task is to generate or refine a single, self-contained, lightweight, mobile-responsive HTML/CSS captive portal page.

CRITICAL DESIGN CONSTRAINTS:
1. Output ONLY a complete, valid, single-file HTML document (<!DOCTYPE html> ... </html>).
2. ALL CSS must be inline inside a <style> tag in <head>. Do NOT link to external CSS or fonts (Bootstrap, Google Fonts, etc.) because the ESP32 access point runs offline.
3. Mobile-First & Responsive: Must render perfectly on mobile smartphones (iOS/Android) and desktop browsers with clean meta viewport.
4. Design Aesthetic: Modern, high-contrast, polished glassmorphism or sleek corporate design with subtle borders, readable font stacks (-apple-system, Roboto), and responsive padding.
5. Defensive & Educational: Create legitimate, professional network access portals, such as Guest Wi-Fi AUPs, Security Assessment Notices, IT Maintenance downtime notices, or Event Welcomes. Never generate deceptive brand credential phishing pages.
6. Return code wrapped in a ```html codeblock.
"""
        
        let userInstruction = """
Operator Design Guidance:
\(prompt)

Current HTML Baseline:
```html
\(currentHtml)
```

Generate the refined or redesigned standalone HTML/CSS page based on the operator's guidance:
"""
        
        var generatedHtml = ""
        
        if settings.aiEngine == .piHarness && piHarness.isAvailable {
            try await piHarness.streamPrompt(prompt: userInstruction, systemPrompt: systemPrompt) { chunk in
                if let delta = chunk.textDelta {
                    generatedHtml += delta
                    onDelta?(delta)
                }
            }
        } else {
            let messages: [[String: Any]] = [
                ["role": "system", "content": systemPrompt],
                ["role": "user", "content": userInstruction]
            ]
            try await openRouter.streamChat(
                messages: messages,
                apiKey: settings.openRouterApiKey,
                model: settings.selectedModel
            ) { chunk in
                if let delta = chunk.textDelta {
                    generatedHtml += delta
                    onDelta?(delta)
                }
            }
        }
        
        // Extract HTML from code block if present
        let cleaned = extractHtmlFromText(generatedHtml)
        if !cleaned.isEmpty {
            self.currentHtml = cleaned
            self.lastStatus = "Portal successfully designed by AI."
            return cleaned
        } else if !generatedHtml.isEmpty {
            self.currentHtml = generatedHtml
            self.lastStatus = "Portal generated."
            return generatedHtml
        } else {
            throw NSError(domain: "CaptivePortalService", code: -2, userInfo: [NSLocalizedDescriptionKey: "No HTML content was generated by model."])
        }
    }
    
    /// Deploy the current HTML directly to Flipper Zero SD card for the wireless devboard.
    public func deployPortalToFlipper(html: String, targetFolder: String = "/ext/apps_data/evil_portal") async throws -> String {
        guard connection.status.isConnected else {
            throw NSError(domain: "CaptivePortalService", code: -3, userInfo: [NSLocalizedDescriptionKey: "Flipper Zero is not connected. Connect via USB or BLE first."])
        }
        
        self.isDeploying = true
        self.lastStatus = "Deploying index.html to Flipper SD card at \(targetFolder)..."
        defer { self.isDeploying = false }
        
        // Ensure destination directories exist
        _ = try? await connection.executeCommand("storage mkdir /ext/apps_data")
        _ = try? await connection.executeCommand("storage mkdir \(targetFolder)")
        
        let targetFilePath = "\(targetFolder)/index.html"
        
        // Write the HTML to the destination file
        _ = try? await connection.executeCommand("storage write \(targetFilePath)")
        let writeResult = try await connection.executeCommand("\(html)\r\n\u{04}") // EOT
        
        // Persist local staging copy next to the app bundle (Resources/portals),
        // falling back to Application Support when running from a .build directory.
        let localDir = Self.portalsStagingDirectory()
        try? FileManager.default.createDirectory(at: localDir, withIntermediateDirectories: true)
        let localFile = localDir.appendingPathComponent("index.html")
        try? html.write(to: localFile, atomically: true, encoding: .utf8)
        
        // Auto-record to Memory Vault
        FerriteSuiteMemoryStore.shared.addMemory(
            category: .hardware,
            title: "Captive Portal Deployed: \(selectedTemplate.title)",
            content: "Staged HTML portal (\(html.count) bytes) to Flipper SD card at \(targetFilePath) and local disk at \(localFile.path)."
        )
        
        self.lastStatus = "✅ Successfully deployed to \(targetFilePath)"
        return "Deployed index.html (\(html.count) bytes) to \(targetFilePath). Output: \(writeResult)"
    }
    
    /// Writable directory for locally staged captive portals.
    ///
    /// Prefers `Contents/Resources/portals` when running from a packaged `.app`,
    /// and falls back to Application Support when running from SwiftPM's
    /// `.build` directory (where there is no bundle to write into).
    private static func portalsStagingDirectory() -> URL {
        let fm = FileManager.default
        if let bundled = Bundle.main.resourceURL?.appendingPathComponent("portals", isDirectory: true),
           fm.isWritableFile(atPath: bundled.path) {
            return bundled
        }
        let support = fm.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
            ?? URL(fileURLWithPath: NSTemporaryDirectory(), isDirectory: true)
        return support.appendingPathComponent("portals", isDirectory: true)
    }

    private func extractHtmlFromText(_ text: String) -> String {
        if let start = text.range(of: "```html"),
           let end = text.range(of: "```", range: start.upperBound..<text.endIndex) {
            return String(text[start.upperBound..<end.lowerBound]).trimmingCharacters(in: .whitespacesAndNewlines)
        }
        if let start = text.range(of: "<!DOCTYPE html"),
           let end = text.range(of: "</html>", options: .backwards) {
            return String(text[start.lowerBound...end.upperBound])
        }
        return text.trimmingCharacters(in: .whitespacesAndNewlines)
    }
}
